### ISSUE TITLE
Failed to init: Unable to find sdk io.elementary.Sdk version 6

### ISSUE THREAD

**Issue by aral** [elementary/docs#126]
When I run `flatpak-builder build org.small-tech.hello-world.yml --user --install --force-clean`, I get the following error: 

```
error: io.elementary.Sdk/x86_64/6 not installed
Failed to init: Unable to find sdk io.elementary.Sdk version 6
```

`apt search elementary-sdk` gives me:

```
elementary-sdk/focal,now 1.508+r576~ubuntu6.1 amd64 [installed]
  elementary Developer Kit
```

My _org.small-tech.hello-world.yml_ file contents are:

```yml
app-id: org.small-tech.hello-world

runtime: io.elementary.Platform
runtime-version: '6'
sdk: io.elementary.Sdk

command: org.small-tech.hello-world

finish-args:
  - '--share=ipc'
  - '--socket=fallback-x11'
  - '--socket=wayland'

modules:
  - name: hello-world
    buildsystem: meson
    sources:
      - type: dir
        path: .
```
